//created on: Apr 25, 2018
package org.healthnlp.deepphe.uima.drools.ov

import java.lang.Object;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Date;

import org.apache.ctakes.cancer.concept.instance.ConceptInstance;

import org.healthnlp.deepphe.util.FHIRUtils;
import org.healthnlp.deepphe.util.FHIRConstants;

import org.healthnlp.deepphe.fact.Fact;
import org.healthnlp.deepphe.fact.ObservationFact;
import org.healthnlp.deepphe.fact.FactFactory;
import org.healthnlp.deepphe.fact.FactHelper;

import org.healthnlp.deepphe.summary.*;
import org.healthnlp.deepphe.uima.drools.*;



//Actually this is a placeholder for possible CA-125 rules

/*
* Set PR status for each tumor with body location
*/
rule "collect-all-tumor-PRStatus"
	salience 67669
	no-loop true
	when 
		$record : MedicalRecord()
		$cancerFact : Fact(summaryType==FHIRConstants.CANCER_SUMMARY, documentType == FHIRConstants.RECORD_SUMMARY)
		
		$tF : Fact(summaryType == FHIRConstants.TUMOR_SUMMARY, documentType != FHIRConstants.RECORD_SUMMARY, 
					$t_summaryId : summaryId, category == FHIRConstants.HAS_BODY_SITE)
	    
	    $recepFact : Fact($name : name, documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.PR_STATUS_PATTERN,
	    			summaryId == $t_summaryId)
	    
	    $mt : MergedTumor($tumorSummaryIdSet : tumorSummaryIdSet, $tumorSummaryIdSet contains $t_summaryId,  
	    			$mergedTumorId : mergedTumorId, rulesApplied not contains "collect-all-tumor-PRStatus")		
	    			
	    $recSet : Set()
	    from collect(Fact(documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.PR_STATUS_PATTERN,
	    			$tumorSummaryIdSet contains summaryId))
		
		$methods :Set()
		from collect(Fact(category == FHIRConstants.HAS_METHOD, $tumorSummaryIdSet contains summaryId))
	    
	then
	
		for(Object recObj : $recSet){
			Fact recFact = (Fact)recObj;
			$mt.addReceptorStatus(recFact, $methods);
			modify(recFact){	addRulesApplied("collect-all-tumor-PRStatus") }
		}
		modify($mt){ addRulesApplied("collect-all-tumor-PRStatus") }
		Fact tf = $mt.getTumorSummaryReceptor(FHIRConstants.HAS_RECEPTOR_STATUS, $recepFact.getName(), $cancerFact);
			if( tf != null){
			    modify($record){
					getCancerSummary().getTumorSummaryByIdentifier(FHIRConstants.TUMOR_SUMMARY +"-"+
								$mergedTumorId).addFact(FHIRConstants.HAS_RECEPTOR_STATUS, tf)
				}
			    tf.addRulesApplied("collect-all-tumor-PRStatus");
			    insert(tf);			    
			}
		System.out.print(".");
	//System.out.println("$$$ collect-all-tumor-PRStatus");	
	
end


/*
* Set ER status for each tumor with body location
*/
rule "collect-all-tumor-ERStatus"
	salience 67667
	no-loop true
	when 
		$record : MedicalRecord()
		$cancerFact : Fact(summaryType==FHIRConstants.CANCER_SUMMARY, documentType == FHIRConstants.RECORD_SUMMARY)
		
		$tF : Fact(summaryType == FHIRConstants.TUMOR_SUMMARY, documentType != FHIRConstants.RECORD_SUMMARY, 
					$t_summaryId : summaryId, category == FHIRConstants.HAS_BODY_SITE)
	    
	    $recepFact : Fact($name : name, documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.ER_STATUS_PATTERN,
	    			summaryId == $t_summaryId)
	    
	    $mt : MergedTumor($tumorSummaryIdSet : tumorSummaryIdSet, $tumorSummaryIdSet contains $t_summaryId,  
	    			$mergedTumorId : mergedTumorId, rulesApplied not contains "collect-all-tumor-ERStatus")	
	    			
	    $recSet : Set()
	    from collect(Fact(documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.ER_STATUS_PATTERN,
	    			$tumorSummaryIdSet contains summaryId))
		
		$methods :Set()
		from collect(Fact(category == FHIRConstants.HAS_METHOD, $tumorSummaryIdSet contains summaryId))
	    
	then
	
		for(Object recObj : $recSet){
			Fact recFact = (Fact)recObj;
			$mt.addReceptorStatus(recFact, $methods);
			modify(recFact){	addRulesApplied("collect-all-tumor-ERStatus") }
		}
		modify($mt){ addRulesApplied("collect-all-tumor-ERStatus") }
		Fact tf = $mt.getTumorSummaryReceptor(FHIRConstants.HAS_RECEPTOR_STATUS, $recepFact.getName(), $cancerFact);
			if( tf != null){
			    modify($record){
					getCancerSummary().getTumorSummaryByIdentifier(FHIRConstants.TUMOR_SUMMARY +"-"+
								$mergedTumorId).addFact(FHIRConstants.HAS_RECEPTOR_STATUS, tf)
				}
			    tf.addRulesApplied("collect-all-tumor-ERStatus");
			    insert(tf);			    
			}
		System.out.print(".");
	//System.out.println("$$$ collect-all-tumor-ERStatus");	
	
end


/*
* Set Her2 status for each tumor with body location
*/
rule "collect-all-tumor-Her2Status"
	salience 67665
	no-loop true
	when 
		$record : MedicalRecord()
		$cancerFact : Fact(summaryType==FHIRConstants.CANCER_SUMMARY, documentType == FHIRConstants.RECORD_SUMMARY)
		
		$tF : Fact(summaryType == FHIRConstants.TUMOR_SUMMARY, documentType != FHIRConstants.RECORD_SUMMARY, 
					$t_summaryId : summaryId, category == FHIRConstants.HAS_BODY_SITE)
	    
	    $recepFact : Fact($name : name, documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.HER2_STATUS_PATTERN,
	    			summaryId == $t_summaryId)
	    
	    $mt : MergedTumor($tumorSummaryIdSet : tumorSummaryIdSet, $tumorSummaryIdSet contains $t_summaryId,  
	    			$mergedTumorId : mergedTumorId, rulesApplied not contains "collect-all-tumor-Her2Status")	
	    			
	    $recSet : Set()
	    from collect(Fact(documentType != FHIRConstants.RECORD_SUMMARY, 
	    			category == FHIRConstants.HAS_INTERPRETATION, name matches FHIRConstants.HER2_STATUS_PATTERN,
	    			$tumorSummaryIdSet contains summaryId))
		
		$methods :Set()
		from collect(Fact(category == FHIRConstants.HAS_METHOD, $tumorSummaryIdSet contains summaryId))
	    
	then
	
		for(Object recObj : $recSet){
			Fact recFact = (Fact)recObj;
			$mt.addReceptorStatus(recFact, $methods);
			modify(recFact){	addRulesApplied("collect-all-tumor-Her2Status") }
		}
		modify($mt){ addRulesApplied("collect-all-tumor-Her2Status") }
		Fact tf = $mt.getTumorSummaryReceptor(FHIRConstants.HAS_RECEPTOR_STATUS, $recepFact.getName(), $cancerFact);
			if( tf != null){
			    modify($record){
					getCancerSummary().getTumorSummaryByIdentifier(FHIRConstants.TUMOR_SUMMARY +"-"+
								$mergedTumorId).addFact(FHIRConstants.HAS_RECEPTOR_STATUS, tf)
				}
			    tf.addRulesApplied("collect-all-tumor-Her2Status");
			    insert(tf);			    
			}
		System.out.print(".");
	//System.out.println("$$$ collect-all-tumor-Her2Status");	
	
end
