name: Copy Code Repositories
on:
  workflow_dispatch:

jobs:
  checkout-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Release repo
        uses: actions/checkout@v7

      - name: Get Desktop
        uses: actions/checkout@v7
        with:
          # Contains dphe Desktop gui
          repository: 'DeepPhe/dphe-gui'
          path: 'dphe-gui'
      - name: Get neo4j API
        uses: actions/checkout@v7
        with:
          # Our api for neo4j
          repository: 'DeepPhe/dphe-neo4j'
          path: 'dphe-neo4j'
      - name: Get Ontology
        uses: actions/checkout@v7
        with:
          # Ontology graph db and synonym db
          repository: 'DeepPhe/dphe-onto-db2'
          path: 'dphe-onto-db2'
      - name: Get Summarizer
        uses: actions/checkout@v7
        with:
          # Summarizer code
          repository: 'DeepPhe/dphe-nlp2'
          path: 'dphe-nlp2'

      - name: Delete git configs
        # The checkout action creates .git folders in each repo directory.
        # This creates broken links in the created branch.
        run: |
          rm -fr dphe-gui/.git
          rm -fr dphe-neo4j/.git
          rm -fr dphe-onto-db2/.git
          rm -fr dphe-nlp2/.git

      - name: Commit to main
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          create_branch: true
          branch: auto-copy
          commit_message: Action-based commit of copies of current dphe repositories
          push_options: '--force'   


